name: perl-Config-Any
upstream: http://search.cpan.org/dist/Config-Any/
description: Load configuration from different file formats, transparently
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
- name: openEuler-24.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-24.03-LTS
  type: protected
  create_from: openEuler-24.03-LTS-Next
type: public
