name: mock-core-configs
description: Mock core config files basic chroots
upstream: https://github.com/rpm-software-management/mock
branches:
- name: master
  type: protected
- name: openEuler-23.09
  type: protected
  create_from: master
type: public
