name: kconfigDetector
description: Tools for detection kernel configuration error values.
upstream: https://gitee.com/openeuler/kconfigDetector
branches:
- name: master
  type: protected
- name: openEuler-23.03
  type: readonly
  create_from: master
- name: openEuler-23.09
  type: protected
  create_from: master
type: public
