name: system-config-users
description: A graphical interface for administering users and groups
upstream: http://fedorahosted.org/system-config-users
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
- name: openEuler-23.03
  type: readonly
  create_from: master
- name: openEuler-23.09
  type: protected
  create_from: master
type: public
