name: python-sphinxcontrib-openapi
description: OpenAPI (fka Swagger) spec renderer for Sphinx.
upstream: https://github.com/sphinx-contrib/openapi
branches:
- name: master
  type: protected
- name: openEuler-24.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-24.03-LTS
  type: protected
  create_from: openEuler-24.03-LTS-Next
type: public
