name: python-pytoolconfig
description: Python Tool Configuration to manage configuration for python tools and
  add support for a pyproject.toml configuration file.
upstream: https://github.com/bageljrkhanofemus/pytoolconfig
branches:
- name: master
  type: protected
- name: openEuler-24.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-24.03-LTS
  type: protected
  create_from: openEuler-24.03-LTS-Next
type: public
