name: python-prometheus-api-client
upstream: https://github.com/AICoE/prometheus-api-client-python
description: A Python wrapper for the Prometheus http api and some tools for metrics
  processing.
branches:
- name: master
  type: protected
- name: openEuler-21.09
  type: readonly
  create_from: master
- name: openEuler-22.03-LTS-Next
  type: protected
  create_from: openEuler-21.09
- name: openEuler-22.03-LTS
  type: protected
  create_from: openEuler-22.03-LTS-Next
- name: openEuler-22.09
  type: readonly
  create_from: master
- name: openEuler-22.03-LTS-SP1
  type: protected
  create_from: openEuler-22.03-LTS-Next
- name: openEuler-23.03
  type: readonly
  create_from: master
- name: openEuler-22.03-LTS-SP2
  type: protected
  create_from: openEuler-22.03-LTS-Next
- name: openEuler-23.09
  type: protected
  create_from: master
- name: openEuler-22.03-LTS-SP3
  type: protected
  create_from: openEuler-22.03-LTS-Next
- name: openEuler-24.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-24.03-LTS
  type: protected
  create_from: openEuler-24.03-LTS-Next
type: public
