name: python-django-configurations
description: A helper for organizing Django settings.
upstream: https://github.com/jazzband/django-configurations
branches:
- name: master
  type: protected
- name: openEuler-22.09
  type: protected
  create_from: master
type: public
