name: rubygem-regexp_property_values
description: This small library lets you see which property values are supported by
  the regular expression engine of the Ruby version you are running, and what they
  match.
upstream: https://github.com/jaynetics/regexp_property_values
branches:
- name: master
  type: protected
- name: openEuler-22.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-22.03-LTS
  type: protected
  create_from: openEuler-22.03-LTS-Next
- name: openEuler-22.09
  type: protected
  create_from: master
- name: openEuler-22.03-LTS-SP1
  type: protected
  create_from: openEuler-22.03-LTS-Next
type: public
